name: cms
description: A tiny layer on top of `bloc` that models your app as **States** `S`, **Actions** `A`, and a **deterministic Markov kernel**.
version: 1.4.4
repository: https://github.com/BoxMeApp/cms

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^9.0.0
  meta: ^1.3.0

dev_dependencies:
  bloc_test: ^10.0.0
  lints: ^6.0.0
  test: ^1.25.6
